In [1]:
import numpy as np

In [46]:
xt = [[1, 2]]
x = [[1],[2]]
print(x)
print(xt)

[[1], [2]]
[[1, 2]]


In [47]:
H = np.dot(x,xt)+1
print(H)
Hi = np.linalg.inv(H)
print(Hi)

[[2 3]
 [3 5]]
[[ 5. -3.]
 [-3.  2.]]


In [48]:
print(np.dot(Hi,x))

[[-1.]
 [ 1.]]
